# -*- coding: utf-8 -*-
"""Estatistica_fraude

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHQBAxx-TPNYhFigG-8RCNulWNLnzHjM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("dataset_reembolsos_simulado.xlsx")

print("Estatísticas Descritivas:")
print(df['Valor'].describe())

plt.figure(figsize=(10, 6))
sns.histplot(df['Valor'], bins=50, kde=True, color='skyblue')
plt.title('Distribuição dos Valores de Reembolso')
plt.xlabel('Valor (R$)')
plt.ylabel('Frequência')
plt.tight_layout()
plt.savefig("grafico_distribuicao_valores.png")
plt.close()

top_gastos = df.groupby("Funcionário")["Valor"].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=top_gastos.values, y=top_gastos.index, palette="viridis")
plt.title("Top 10 Funcionários que Mais Gastam")
plt.xlabel("Total Gasto (R$)")
plt.ylabel("Funcionário")
plt.tight_layout()
plt.savefig("grafico_top10_gastos.png")
plt.close()


top_reembolsos = df["Funcionário"].value_counts().head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=top_reembolsos.values, y=top_reembolsos.index, palette="magma")
plt.title("Top 10 Funcionários com Mais Reembolsos (Quantidade)")
plt.xlabel("Quantidade de Reembolsos")
plt.ylabel("Funcionário")
plt.tight_layout()
plt.savefig("grafico_top10_reembolsos.png")
plt.close()

plt.figure(figsize=(10, 6))
sns.countplot(data=df, y="Tipo de Despesa", order=df["Tipo de Despesa"].value_counts().index, palette="pastel")
plt.title("Reembolsos por Tipo de Despesa")
plt.xlabel("Quantidade")
plt.ylabel("Tipo de Despesa")
plt.tight_layout()
plt.savefig("grafico_reembolsos_por_tipo.png")
plt.close()

plt.figure(figsize=(10, 6))
sns.countplot(data=df, y="Departamento", order=df["Departamento"].value_counts().index, palette="coolwarm")
plt.title("Reembolsos por Departamento")
plt.xlabel("Quantidade")
plt.ylabel("Departamento")
plt.tight_layout()
plt.savefig("grafico_reembolsos_por_departamento.png")
plt.close()

df['Data'] = pd.to_datetime(df['Data'])
df['AnoMes'] = df['Data'].dt.to_period('M').astype(str)
reembolsos_mensais = df.groupby("AnoMes")["Valor"].sum()

plt.figure(figsize=(12, 6))
sns.lineplot(x=reembolsos_mensais.index, y=reembolsos_mensais.values, marker="o", color='dodgerblue')
plt.xticks(rotation=45)
plt.title("Evolução dos Reembolsos por Mês")
plt.xlabel("Ano-Mês")
plt.ylabel("Valor Total Reembolsado (R$)")
plt.tight_layout()
plt.savefig("grafico_evolucao_mensal.png")
plt.close()

